# Generated by Django 5.1.3 on 2025-06-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='updted_at',
            new_name='updated_at',
        ),
    ]
