# Generated by Django 5.1.3 on 2025-08-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chatanswers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatAnswers',
            new_name='ChatAnswer',
        ),
    ]
